---
- name: Remove Phone
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}:8443/axl/"
    method: POST
    headers:
      Content-Type: text/xml
      SOAPAction: '"CUCM:DB ver={{ axl_version }} removePhone"'
    force_basic_auth: true
    user: "{{ hostvars[ansible_host].axl_user }}"
    password: "{{ hostvars[ansible_host].axl_password }}"
    body: >-
      <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://www.cisco.com/AXL/API/{{ axl_version }}">
        <soapenv:Body>
          <ns:removePhone sequence="1">
            <name>{{ device_name | default('SEP123456789012') }}</name>
          </ns:removePhone>
        </soapenv:Body>
      </soapenv:Envelope>
    validate_certs: false
    return_content: true
    status_code:
      - 200
      - 500
  register: response
  changed_when: response.status == 200
  failed_when: response.status == 500 and '<axlcode>-239' not in response.content
